version: 0.2

phases:
	pre_build:
		commands:
			- npm install
			- npm test
			
  build:
    commands:
      - npm run webpack

artifacts:
  files:
    - favicon.ico
    - images/*
    - styles/*
    - example.txt
    - ThomasBridge.CV.pdf
    - ./*.html
    - subdir/*
    - dist/bundle.js

