version: 0.2

phases:
  build:
    commands:
      - echo Nothing to do yet

artifacts:
  files:
    - favicon.ico
    - images/*
    - styles/*
    - example.txt
    - ThomasBridge.CV.pdf
    - *.html